### ISSUE TITLE
如何获取pod的生命周期各个event的耗时

### ISSUE THREAD

**Issue by chenpfeisoo** [yzs981130/PodEventLogger#1]
请教一下 ，如何获取pod的生命周期各个event的耗时
比如 pod  image pull 耗时
      pod 调度耗时
      pod start 耗时等

**Comment by yzs981130** [comment]
建议是直接带时间戳打出相应的event，然后后续单独统计分析。image是有pulling和pulled两个event的，调度和start应该都只有scheduled和successful create，应该只能根据前后event统计分析

**Comment by chenpfeisoo** [comment]
是的，我是通过 fmt.Println(event.LastTimestamp.Time.Sub(event.CreationTimestamp.Time), "\t")来计算耗时的，但是有很多 event算出来的是0
